---
  name: "balance-transfer"
  x-type: "hlfv1"
  description: "Balance Transfer Network"
  version: "1.0"
  channels:
    mychannel:
      orderers:
        - orderer.example.com:17050
      peers:
        peer0.org1.example.com:
          endorsingPeer: true
          chaincodeQuery: true
          ledgerQuery: true
          eventSource: true
          
  organizations:
    Org1:
      mspid: Org1MSP
      peers:
        - peer0.org1.example.com
      certificateAuthorities:
        - ca.org1.example.com

  orderers:
    orderer.example.com:
      url: grpcs://localhost:17050
      grpcOptions:
        ssl-target-name-override: orderer.example.com
  
  peers:
    peer0.org1.example.com:
      # this URL is used to send endorsement and query requests
      url: grpc://localhost:17051
      eventUrl: grpc://localhost:17052
      grpcOptions:
        ssl-target-name-override: peer0.org1.example.com
  
  certificateAuthorities:
    ca.org1.example.com:
      url: http://localhost:17054
      caName: ca.org1.example.com